name = "lakeshore_website"
pages_build_output_dir = "./build"

compatibility_date = "2025-08-06"

# Runtime environment variables
[vars]
REACT_APP_API_URL = "https://lakeshore-emailer.netlify.app/.netlify/functions/send-email"
REACT_APP_TO_EMAIL = "jmpiltz@gmail.com"

# environment-specific sections
[env.production.vars]
REACT_APP_API_URL = "https://lakeshore-emailer.netlify.app/.netlify/functions/send-email"
REACT_APP_TO_EMAIL = "jmpiltz@gmail.com"